<?php

use Illuminate\Database\Seeder;
use App\Incubator;

class IncubatorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('incubators')->truncate();
        Schema::enableForeignKeyConstraints();

        $incubators = [

            [
                'name'=> 'IC406',
                'image'=> 'incubators/ic406.svg',
                'website'=> 'https://www.ic406.com/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'K HUB - Knowledge Accelerator',
                'image'=> 'incubators/cropped-logo-KHub-Bianco-Rid-1.png',
                'website'=> 'https://www.knowledge-hub.it/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Digital Borgo',
                'image'=> 'incubators/digitalb.png',
                'website'=> 'http://www.digitalborgo.com/',
                'country_id'=> 1,
                'region_id'=> 1,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'The Hive Pescara',
                'image'=> 'incubators/unnamed-2.webp',
                'website'=> 'https://www.the-hive.it/',
                'country_id'=> 1,
                'region_id'=> 1,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Sistema IncHUBatori',
                'image'=> 'incubators/sistemaincubatori.png',
                'website'=> 'https://www.sistemaincubatori.it/',
                'country_id'=> 1,
                'region_id'=> 2,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Tech Nest',
                'image'=> 'incubators/technest.webp',
                'website'=> 'https://www.unical.it/innovazione-societa/trasferimento-tecnologico/creazione-imprese-innovative/technest/',
                'country_id'=> 1,
                'region_id'=> 3,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Sellalab',
                'image'=> 'incubators/Logo-Sellalab-0033cc.png',
                'website'=> 'https://sellalab.com/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Campania NewSteel',
                'image'=> 'incubators/logo_CNS_full.png',
                'website'=> 'https://www.campanianewsteel.it/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Centro Il Faro',
                'image'=> 'incubators/centroilfaro.jpg',
                'website'=> 'http://www.il-faro.com/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Centro Servizi Incubatore Napoli Est',
                'image'=> 'incubators/csi1.png',
                'website'=> 'https://www.incubatorenapoliest.it/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Digital Magics Napoli',
                'image'=> 'incubators/digitalmagicss.png',
                'website'=> 'https://www.digitalmagics.com/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Hub Spa',
                'image'=> 'incubators/LOGO-BIANCO_Tavola-disegno-1.png',
                'website'=> 'https://www.hubspa.it/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'NAStartUp',
                'image'=> 'incubators/nastartup-brand-2021-1.png',
                'website'=> 'https://www.nastartup.it/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Seedup',
                'image'=> 'incubators/logo75-1.png',
                'website'=> 'http://www.seedup.it/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> '012Factory',
                'image'=> 'incubators/012-logooo.png',
                'website'=> 'https://www.012factory.it/',
                'country_id'=> 1,
                'region_id'=> 4,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Primo Miglio',
                'image'=> 'incubators/primomiglio.png',
                'website'=> 'https://www.primomigliostartup.com/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Upidea!',
                'image'=> 'incubators/upidea.png',
                'website'=> 'http://www.upidea.it/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'U-start incubatore',
                'image'=> 'incubators/ustart.png',
                'website'=> 'https://www.ustart.it/incubatore',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'VZ19 Startup Factory',
                'image'=> 'incubators/vz19-logo.png',
                'website'=> 'http://vz19.it/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'inLab',
                'image'=> 'incubators/prohub.png',
                'website'=> 'https://www.h-prohub.com/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'i9factory',
                'image'=> 'incubators/logoi9factory-1-1.jpg',
                'website'=> 'https://www.i9factory.it/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Lugo Next Lab',
                'image'=> 'incubators/lugonextlab.png',
                'website'=> 'https://www.lugonextlab.eu/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'U-Start',
                'image'=> 'incubators/ustartt.png',
                'website'=> 'https://www.ustart.it/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Innovami',
                'image'=> 'incubators/innovami.png',
                'website'=> 'https://www.innovami.it/it/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'RomagnaTech Forlì',
                'image'=> 'incubators/logo_romagnatech.png',
                'website'=> 'https://www.romagnatech.eu/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Sipro',
                'image'=> 'incubators/logo_Sipro_colore_34634.jpg',
                'website'=> 'https://www.siproferrara.com/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Cesena Lab',
                'image'=> 'incubators/Cesena-Lab-Logo.svg',
                'website'=> 'https://www.cesenalab.it/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Gellify',
                'image'=> 'incubators/gellify-logo-trasparente.png',
                'website'=> 'https://www.gellify.com/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Almacube',
                'image'=> 'incubators/unnamed.jpg',
                'website'=> 'https://www.almacube.com/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Climate-KIC Startup Accelerator Italy',
                'image'=> 'incubators/logo-white-wFlag2.svg',
                'website'=> 'https://italy.climate-kic.org/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Co-start',
                'image'=> 'incubators/costartt.jpg',
                'website'=> 'https://www.villagaragnani.it/co-start',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'G Factor',
                'image'=> 'incubators/logo1585132647aa.jpg',
                'website'=> 'https://www.fondazionegolinelli.it/it/area-impresa/g-factor',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Le Serre',
                'image'=> 'incubators/LeSerrediArter.png',
                'website'=> 'https://www.aster.it/attivita/ecosistema-dellinnovazione/gli-incubatori-e-le-serre-di-aster',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Youcangroup',
                'image'=> 'incubators/youcangroup-02.png',
                'website'=> 'https://youcangroup.it/',
                'country_id'=> 1,
                'region_id'=> 5,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Friuli Innovazione',
                'image'=> 'incubators/friuliinnovazione.png',
                'website'=> 'https://friulinnovazione.it/it/',
                'country_id'=> 1,
                'region_id'=> 6,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'AreaScience Park',
                'image'=> 'incubators/IF_LOGO-def-21.png',
                'website'=> 'https://if.areasciencepark.it/',
                'country_id'=> 1,
                'region_id'=> 6,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'BIC Incubatori FVG',
                'image'=> 'incubators/fvg.jpg',
                'website'=> 'https://www.incubatori.fvg.it/it/',
                'country_id'=> 1,
                'region_id'=> 6,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Polo Tecnologico Alto Adriatico',
                'image'=> 'incubators/logo_polo.svg',
                'website'=> 'https://www.polotecnologicoaltoadriatico.it/',
                'country_id'=> 1,
                'region_id'=> 6,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Agenzia Spaziale Italiana',
                'image'=> 'incubators/logo-asi-white.png',
                'website'=> 'https://www.asi.it/2020/10/spacecom-entrepreneur-summit-di-houston-spazio-alle-start-up-italiane/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Coopup',
                'image'=> 'incubators/logo_coopup.png',
                'website'=> 'https://www.coopup.net/#top',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Digital Magics Roma',
                'image'=> 'incubators/digitalmagicss.png',
                'website'=> 'https://www.digitalmagics.com/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'dock3',
                'image'=> 'incubators/Logo_dock_3.png',
                'website'=> 'https://www.dock3.it/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Elis Open Italy',
                'image'=> 'incubators/openitaly.png',
                'website'=> 'https://open-italy.elis.org/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Enea',
                'image'=> 'incubators/logoENEA.png',
                'website'=> 'https://www.enea.it/it',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Fondazione ItaliaCamp',
                'image'=> 'incubators/Italiacamp_logo.png',
                'website'=> 'https://italiacamp.com/it/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Impact Hub Rome',
                'image'=> 'incubators/impacthub.svg',
                'website'=> 'https://rome.impacthub.net/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Tecnopolo Roma',
                'image'=> 'incubators/Tecnopolo-Brand-Manual-7.png',
                'website'=> 'https://www.tecnopolo.it/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Luiss Enlabs Roma',
                'image'=> 'incubators/luiss.png',
                'website'=> 'http://luissenlabs.com/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Mobilityup',
                'image'=> 'incubators/MobiltyUP_final_trasp3.gif',
                'website'=> 'https://www.mobilityup.com/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Pi Campus',
                'image'=> 'incubators/logo-picampus-2.webp',
                'website'=> 'https://picampus.it/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Startalia',
                'image'=> 'incubators/startalia-logo-red-300.png',
                'website'=> 'https://startalia.com/home.aspx',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Startupbootcamp FoodTech',
                'image'=> 'incubators/SBC-FoodTech_white.png',
                'website'=> 'https://www.startupbootcamp.org/accelerator/foodtech-rome/',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Go Beyond - Sisal',
                'image'=> 'incubators/logo-home-white.png',
                'website'=> 'https://www.gobeyond.info/it',
                'country_id'=> 1,
                'region_id'=> 7,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Wylab',
                'image'=> 'incubators/Wylab-logo-greywhite.svg',
                'website'=> 'https://wylab.net/',
                'country_id'=> 1,
                'region_id'=> 8,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'B4I - Bocconi for innovation',
                'image'=> 'incubators/bocconi.svg',
                'website'=> 'https://www.b4i.unibocconi.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'BioUpper',
                'image'=> 'incubators/cariplo-factory@3x-300x174.png',
                'website'=> 'https://bioupper.cariplofactory.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'BiovelocITA',
                'image'=> 'incubators/logo-biovelocita-ft.png',
                'website'=> 'https://www.biovelocita.com/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Boox',
                'image'=> 'incubators/Logo_Boox_42731.jpg',
                'website'=> 'http://www.boox.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Breed Reply',
                'image'=> 'incubators/breed-reply-logo.png',
                'website'=> 'https://www.reply.com/breed-reply/en/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Credite Agricole LE VILLAGE',
                'image'=> 'incubators/Logo_slider_black5.png',
                'website'=> 'https://levillagebyca.it/it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Deloitte - FoodTech accelerator',
                'image'=> 'incubators/foodta.png',
                'website'=> 'https://www.foodtechaccelerator.io/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Digitalmagics Milano',
                'image'=> 'incubators/digitalmagicss.png',
                'website'=> 'https://www.digitalmagics.com/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Endeavor',
                'image'=> 'incubators/endeavor.jpg',
                'website'=> 'https://endeavoritaly.org/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'E-Novia',
                'image'=> 'incubators/enovia_logo_white.svg',
                'website'=> 'https://e-novia.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Fashion Technology Accelerator',
                'image'=> 'incubators/fashiont.svg',
                'website'=> 'https://www.ftaccelerator.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Fondazione Filarete',
                'image'=> 'incubators/filarete.jpg',
                'website'=> 'https://www.fondazionefilarete.com/it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Fondazione ItaliaCamp',
                'image'=> 'incubators/Italiacamp_logo.png',
                'website'=> 'https://italiacamp.com/it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Fondazione Social Venture Giordano Dell\'Amore',
                'image'=> 'incubators/logo_FSV_GiordanoDellAmore.svg',
                'website'=> 'https://www.fondazionesocialventuregda.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'G2-Startups',
                'image'=> 'incubators/G2_RGB_80.png',
                'website'=> 'https://g2-startups.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'growITup',
                'image'=> 'incubators/GrowITUp_marchio_pos_CMYK_40127.jpg',
                'website'=> 'https://www.growitup.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'IBM Studios',
                'image'=> 'incubators/logo-IBM-1962.png',
                'website'=> 'https://www.ibm.com/easytools/runtime/hspx/prod/public/X0027/PortalX/page/pageTemplate?s=72fb24681f2b473dad6b32d6c3146164&c=72fb24681f2b473dad6b32d6c3146164',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Impacthub Milano',
                'image'=> 'incubators/logo-mainim.svg',
                'website'=> 'https://milan.impacthub.net/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Innovits',
                'image'=> 'incubators/InnoVits-logo.png',
                'website'=> 'https://innovits.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Italian Brand Factory',
                'image'=> 'incubators/italianbrand.png',
                'website'=> 'http://www.italianbrandfactory.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Key Capital',
                'image'=> 'incubators/keyc.png',
                'website'=> 'http://keycapital.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Makeacube',
                'image'=> 'incubators/acube-bianco.png',
                'website'=> 'https://acube.avanzi.org/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Nuvolab',
                'image'=> 'incubators/nuvolab.svg',
                'website'=> 'https://nuvolab.com/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Plug & Play',
                'image'=> 'incubators/plug-and-play-logo-blue.451860baa333.png',
                'website'=> 'https://www.plugandplaytechcenter.com/milan/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Polihub',
                'image'=> 'incubators/polihub.png',
                'website'=> 'https://www.polihub.it/it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Sellalab',
                'image'=> 'incubators/sellalab.png',
                'website'=> 'https://sellalab.com/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'TalentGarden',
                'image'=> 'incubators/tag-orange.svg',
                'website'=> 'https://talentgarden.org/it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Unicredit Start Lab',
                'image'=> 'incubators/logoStlb.png',
                'website'=> 'https://www.unicreditstartlab.eu/it.html',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'PTP Science Park',
                'image'=> 'incubators/logo_ptp_w.png',
                'website'=> 'https://www.ptp.it/it/incubatore',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'BeMyCompany',
                'image'=> 'incubators/bemycompany-logo.png',
                'website'=> 'https://www.bemycompany.com/web/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Comonext',
                'image'=> 'incubators/comenext.png',
                'website'=> 'https://www.comonext.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Bio4Dreams',
                'image'=> 'incubators/logo_spec.png',
                'website'=> 'https://www.bio4dreams.com/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Open Accelerator',
                'image'=> 'incubators/OA_Logo_bianco.png',
                'website'=> 'https://www.openaccelerator.it/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'D-Namic',
                'image'=> 'incubators/d-namic.webp',
                'website'=> 'http://www.d-namic.it/accelerator/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Superpartes',
                'image'=> 'incubators/superpa.png',
                'website'=> 'https://www.superpartes.biz/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Incubatore d\'Impresa',
                'image'=> 'incubators/incubatore_logo_orizz.png',
                'website'=> 'https://www.incubatore.bergamo.it/sito/index.php',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Kilometro Rosso',
                'image'=> 'incubators/kmr-logo.svg',
                'website'=> 'https://www.kilometrorosso.com/',
                'country_id'=> 1,
                'region_id'=> 9,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'BpCube',
                'image'=> 'incubators/BP-CUBE-INNOVATION-DISTRICT-black-logo-pesaro.webp',
                'website'=> 'https://www.bpcube.com/index.php/it/',
                'country_id'=> 1,
                'region_id'=> 10,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> '2i3t',
                'image'=> 'incubators/2i3t.png',
                'website'=> 'https://www.2i3t.it/',
                'country_id'=> 1,
                'region_id'=> 12,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Build it Up',
                'image'=> 'incubators/builditup.webp',
                'website'=> 'https://www.builditup.it/',
                'country_id'=> 1,
                'region_id'=> 12,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'i3p Incubatore del Politecnico',
                'image'=> 'incubators/i3P logo bianco.svg',
                'website'=> 'https://www.i3p.it/',
                'country_id'=> 1,
                'region_id'=> 12,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Socialfare Impresa Sociale',
                'image'=> 'incubators/socialfare_logo.png',
                'website'=> 'https://socialfare.org/',
                'country_id'=> 1,
                'region_id'=> 12,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Enne3',
                'image'=> 'incubators/enne3.png',
                'website'=> 'http://www.enne3.it/',
                'country_id'=> 1,
                'region_id'=> 12,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Sellalab Biella',
                'image'=> 'incubators/Logo-Sellalab-0033cc.png',
                'website'=> 'https://sellalab.com/coworking-biella/',
                'country_id'=> 1,
                'region_id'=> 12,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Sellalab Lecce',
                'image'=> 'incubators/Logo-Sellalab-0033cc.png',
                'website'=> 'https://sellalab.com/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'The Qube',
                'image'=> 'incubators/LOGO-THE-QUBE-WHITE.png',
                'website'=> 'https://theqube.eu/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Digital Magics Bari',
                'image'=> 'incubators/digitalmagicss.png',
                'website'=> 'https://www.digitalmagics.com/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Impact Hub Bari',
                'image'=> 'incubators/impactbari.svg',
                'website'=> 'https://bari.impacthub.net/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Puglia Startup',
                'image'=> 'incubators/Logo_PugliaStartup.png',
                'website'=> 'https://www.pugliastartup.it/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Item Hub',
                'image'=> 'incubators/item-hub-logo2.png',
                'website'=> 'https://www.itemhub.it/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Vivaio Digitale',
                'image'=> 'incubators/logo_vivaiodigitale_ios.png',
                'website'=> 'https://vivaiodigitale.it/',
                'country_id'=> 1,
                'region_id'=> 13,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Incubatore d\'impresa CubACT',
                'image'=> 'incubators/cubact_slide_0.png',
                'website'=> 'https://www.uniss.it/innovazione-e-societa/innovazione-e-impresa/incubatore',
                'country_id'=> 1,
                'region_id'=> 14,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Clhub',
                'image'=> 'incubators/chub.png',
                'website'=> 'http://www.clhub.biz/',
                'country_id'=> 1,
                'region_id'=> 14,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'The Net Value',
                'image'=> 'incubators/logo-tnv-vettoriale-dark.png',
                'website'=> 'https://www.thenetvalue.com/',
                'country_id'=> 1,
                'region_id'=> 14,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Consorzio Arca',
                'image'=> 'incubators/arca.png',
                'website'=> 'http://www.consorzioarca.it/index.php/it/',
                'country_id'=> 1,
                'region_id'=> 15,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Digital Magics Palermo',
                'image'=> 'incubators/digitalmagicss.png',
                'website'=> 'https://www.digitalmagics.com/',
                'country_id'=> 1,
                'region_id'=> 15,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'BicSicilia',
                'image'=> 'incubators/logoBICSicilia200_BIANCO-TRASPARENTE.png',
                'website'=> 'https://bicsicilia.com/',
                'country_id'=> 1,
                'region_id'=> 15,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Vulcanic',
                'image'=> 'incubators/vulcanic.png',
                'website'=> 'https://www.vulcanic.it/incubatore/',
                'country_id'=> 1,
                'region_id'=> 15,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Bio-incubatore Toscana Life Sciences',
                'image'=> 'incubators/logotls.png',
                'website'=> 'http://www.toscanalifesciences.org/it/bioincubatore/',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Digital Hub',
                'image'=> 'incubators/digihub.png',
                'website'=> 'https://www.digital-hub.it/',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Incubatore del Polo Tecnologico Lucchese',
                'image'=> 'incubators/poloteclucc.jpg',
                'website'=> 'https://www.polotecnologicolucchese.it/entra-nel-polo/incubatore-imprese-innovative/',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Grosseto Sviluppo',
                'image'=> 'incubators/grossetosv.jpg',
                'website'=> 'http://www.grossetosviluppo.it/',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Incubatore universitario UniFi',
                'image'=> 'incubators/unifi.svg',
                'website'=> 'https://www.unifi.it/CMpro-v-p-5965.html',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Murate Idea Park',
                'image'=> 'incubators/murate-idea-park-logo-negativo-big2.png',
                'website'=> 'https://murateideapark.it/',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Nana Bianca',
                'image'=> 'incubators/logo-NB@2x.png',
                'website'=> 'https://nanabianca.it/',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Incubatore del Polo Tecnologico Magona',
                'image'=> 'incubators/logo_italiaqw.jpg',
                'website'=> 'http://www.polomagona.it/',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Innovare in Mugello',
                'image'=> 'incubators/mugello.jpg',
                'website'=> 'https://www.uc-mugello.fi.it/servizi/scheda-servizio/incubatore-di-imprese-innovare-in-mugello',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Incubatore del polo Tecnologico di Navacchio',
                'image'=> 'incubators/pdfg.png',
                'website'=> 'https://www.polotecnologico.it/lincubatore-cresce/',
                'country_id'=> 1,
                'region_id'=> 16,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Hit Hub innovazione Trentino',
                'image'=> 'incubators/hit.png',
                'website'=> 'https://www.trentinoinnovation.eu/it/home-2/',
                'country_id'=> 1,
                'region_id'=> 17,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Infinity Hub',
                'image'=> 'incubators/infinityhub-logo-big.png',
                'website'=> 'https://www.infinityhub.it/',
                'country_id'=> 1,
                'region_id'=> 17,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Trentino Social Tank',
                'image'=> 'incubators/tank.png',
                'website'=> 'https://www.trentinosocialtank.it/',
                'country_id'=> 1,
                'region_id'=> 17,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Industrio Ventures',
                'image'=> 'incubators/Industrio.png',
                'website'=> 'https://industrio.co/',
                'country_id'=> 1,
                'region_id'=> 17,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Progetto Manifattura',
                'image'=> 'incubators/md_logo.png',
                'website'=> 'https://progettomanifattura.it/',
                'country_id'=> 1,
                'region_id'=> 17,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Trentino Sviluppo',
                'image'=> 'incubators/LOGO_TRENTINO_SVILUPPO_TRASPARENTE.png',
                'website'=> 'https://trentinosviluppo.it/',
                'country_id'=> 1,
                'region_id'=> 17,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'IDM',
                'image'=> 'incubators/idm_suedtirol_logo_zugeschnitten.png',
                'website'=> 'https://www.idm-suedtirol.com/it/',
                'country_id'=> 1,
                'region_id'=> 17,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Day One',
                'image'=> 'incubators/dayone-logo-home-inline.png',
                'website'=> 'https://www.day-one.biz/',
                'country_id'=> 1,
                'region_id'=> 20,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'MAG',
                'image'=> 'incubators/logo_mag.jpg',
                'website'=> 'https://magverona.it/la-mag/incubatore-solidale/',
                'country_id'=> 1,
                'region_id'=> 20,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Vega Park',
                'image'=> 'incubators/vega.svg',
                'website'=> 'https://www.vegapark.ve.it/incubatore/',
                'country_id'=> 1,
                'region_id'=> 20,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'H Farm',
                'image'=> 'incubators/HFARM.svg',
                'website'=> 'https://www.h-farm.com/it',
                'country_id'=> 1,
                'region_id'=> 20,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Digital Magics Triveneto',
                'image'=> 'incubators/digitalmagicss.png',
                'website'=> 'https://www.digitalmagics.com/',
                'country_id'=> 1,
                'region_id'=> 20,
                'page_id'=> null,
                'hidden'=>null,
            ],
            [
                'name'=> 'Startcube',
                'image'=> 'incubators/LOGO-STARTCUBE-WHITE.png',
                'website'=> 'https://www.startcube.it/',
                'country_id'=> 1,
                'region_id'=> 20,
                'page_id'=> null,
                'hidden'=>null,
            ],

        ];

        foreach ($incubators as $incubator){
            $new_incubator = new Incubator();
            $new_incubator->name = $incubator['name'];
            $new_incubator->image = $incubator['image'];
            $new_incubator->website = $incubator['website'];
            $new_incubator->country_id = $incubator['country_id'];
            $new_incubator->region_id = $incubator['region_id'];
            $new_incubator->page_id = $incubator['page_id'];
            $new_incubator->hidden = $incubator['hidden'];
            $new_incubator->save();
        }
    }
}
